services:
  db:
    image: postgres:18
    container_name: ramblrdb
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  pgdata: